apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.20.2
        name: nginx
        args:
        - nginx-debug
        - -g
        - daemon off;
        volumeMounts:
        - name: nginxconf
          mountPath: /etc/nginx/conf.d
        - name: serverselectionhtmls
          mountPath: /usr/share/nginx/html/server_selection
        - name: jumphtmls
          mountPath: /usr/share/nginx/html/jump
      volumes:
      - name: nginxconf
        configMap:
          name: nginxconf
      - name: serverselectionhtmls
        configMap:
          name: serverselectionhtmls
      - name: jumphtmls
        configMap:
          name: jumphtmls
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: nginx
  type: NodePort
