apiVersion: v1
data:
  another_whoops.html: |
    another whoops!
  index.html: |
    not jumped
  index_another_fallback.html: |
    another one(fallback)
  index_fallback.html: |
    fallback here
  index_rewrite.html: |
    rewrite hell
  rewrited.html: |
    can you here?
  whoops.html: |
    whoops..(can you here?)
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: jumphtmls
  namespace: nginx
